apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: postgres-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
  {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
  {{- end }}
  selector:
    app.kubernetes.io/name: postgres
