{{ if  .Values.db.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
{{ end }}