kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernets.io/name: postgres-config
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: {{ .Values.db.user }}
  PGGSSENCMODE: disable